### PR TITLE
Update bs-react-native to v 0.8.0

### PR DESCRIPTION
**Pull request by broerjuang**
- [x] update to bs-react-native v 0.8.0
- [x] update docs to match with current bs-react-native

### CODE REVIEW

**Comment by knowbody** [comment]
@broerjuang Thank you for the contribution! That's the first one outside of Callstack 🎉

**Comment by broerjuang** [comment]
it's made my day! would love to learn more into the codebase, and happy to help more! 🎉

**Comment by knowbody** [comment]
feel free to ping me anytime, either [Twitter](https://twitter.com/matzatorski) or join our [Discord channel](https://discord.gg/8DW7b4N)

**Comment by grabbou** [comment]
Thank you @broerjuang and welcome on board!

**Pull request merged**
