### PR TITLE
Adds note to readme re: #103

### PR DESCRIPTION
**Pull request by hew**

### CODE REVIEW

**Comment by leomayleomay** [comment]
since the .js files will be generated alongside the .re files, no .js files will go to lib/js directory, I reckon that will break the build.
another thing is once you specify `package-specs` as an object, you will have to specify `module` in it as well, it's `commonjs` by default.

**Comment by leomayleomay** [comment]
@hew I am wondering if it fails for you once you have `package-specs` added to bsconfig.json, it breaks mine since no .js files go to `lib/js` folder, would love to know if that happens to you

**Comment by knowbody** [comment]
thank you for the PR @hew!

**Comment by hew** [comment]
@knowbody No prob!

**Pull request merged**
